### ISSUE TITLE
yum or pgdg option?

### ISSUE THREAD

**Issue by MichaelDBA** [galaxyproject/ansible-postgresql#34]
Right now it seems the flexible apt and pgdg options are available for debian apt-based systems, but not for redhat based ones.  Any plan to fix this?  Or is this related to the mirror problem, 

redhat.yml file contents snippet:
```
# Not supported (and no good workaround) until there is a solution for https://github.com/ansible/ansible/issues/41178
# - name: Ensure that only the desired PostgreSQL version's repo is enabled
#   yum_repository:
#     name: item.repoid
#     enabled: "{{ (item.repoid == 'pgdg' ~ __postgresql_version_dotless) if item.repoid.startswith('pgdg') else item.state == 'enabled' }}"
#   # "{{ __postgresql_yum_repolist_result.results | selectattr('repoid', 'startswith', 'pgdg') | list }}" would be nice
#   # here but alas there is no `startswith` test
#   loop: "{{ __postgresql_yum_repolist_result.results }}"

```

**Comment by MichaelDBA** [comment]
Is this repo being maintained?

**Comment by hlovdal** [comment]
Well, the repo file is just a text file in ini format, so I do not see anything preventing to use [ansible.builtin.lineinfile](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html) or [community.general.ini_file](https://docs.ansible.com/ansible/latest/collections/community/general/ini_file_module.html) to modify the line with `enabled=...` instead.
