### ISSUE TITLE
WAL archive failed

### ISSUE THREAD

**Issue by pejuam** [galaxyproject/ansible-postgresql#8]
We're getting this every night at 1am:

`execuing rsync --ignore-existing -ptg pg_xlog/0000000100000000000000C8 /postgresql-backups/current/wal failed with code 12:
rsync: change_dir#3 "/postgresql-backups/current" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(625) [Receiver=3.0.9]
rsync: connection unexpectedly closed (9 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]`

I wonder if this went broken in commit `de74a37e1343ded91ac6995afa21244570961a01` where creating backup dir with mkdir -p was removed.

Or do we have something else wrong here?

**Comment by MichaelDBA** [comment]
Any reason why this issue has not been addressed?

**Comment by hexylena** [comment]
@pejuam 
> where creating backup dir with mkdir -p was removed.

This should not have been necessary as ansible now creates the full path if path components are missing. But now @natefoo has rewritten the WAL portion recently so if this had not been working, it should be now.

@MichaelDBA this role is maintained by a handful of academics, we have very limited time.

**Comment by MichaelDBA** [comment]
Thanks for the update, @hexylena
